name: Build project and upload artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build LibOrbisPkg.sln
    - name: Release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LibOrbisPkg
        path: |
          .\*
